[package]
name = "offcut-api-types"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
offcut-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
ts-rs = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
